services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    container_name: "client"
    env_file: ./client/.env
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped
